server:
  port: 7900

spring:
  application:
    name: ai-talk

  # 数据库配置
  datasource:
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 20
      keepalive-time: 30000
    url: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/ai_talk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources.add-mappings: false

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    banner: false

logging:
  level:
    info.mengnan.aitalk.repository.mapper: OFF
    info.mengnan.aitalk.server.config.info.mengnan.aitalk.repository.config.SqlLogInterceptor: INFO
    org.springframework.web: INFO
    info.mengnan.aitalk: INFO

# Elasticsearch配置
elasticsearch:
  host: ${ES_HOST:127.0.0.1}
  port: ${ES_PORT:9200}
  username: ${ES_USERNAME:}
  password: ${ES_PASSWORD:}

# 文件存储路径
file:
  upload-dir: ./uploads

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: jwt
  jwt-secret-key: ${sa-token.secret-key}
  is-log: false
  is-print: false
  is-read-cookie: false
  is-read-header: true
  token-prefix: Bearer
